name: release

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Version
      shell: bash
      id: get-version
      run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"
    - name: Create Versioned Release
      id: create_versioned_release
      uses: ncipollo/release-action@v1
      if: endsWith(github.ref, 'main')
      with:
        allowUpdates: true
        name: Release ${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.get-version.outputs.version }}
